config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'skills#index'
  resources :skills do
    resources :projects
  end
  resources :blogs do
    resources :comments
  end

  resources :users do
    resources :comments
  end

  resources :my_references
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  belongs_to :user
  validates :body, :presence => true
end

app/models/my_reference.rb
class My_reference < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill
  validates :name, :presence => true
  validates :link, :presence => true
  validates :description, :presence => true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :admin) }
  end

    def user_admin
      if current_user
        if current_user.admin === true
          @user_admin = current_user
        end
      end
    end

    helper_method :user_admin
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    @comments = Comment.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new()
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save()
    respond_to do |format|
      format.html { redirect_to blogs_path }
      format.js
    end
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      respond_to do |format|
        format.html { redirect_to blogs_path }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_path }
      format.js
    end
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def index
    @comments = Comment.all
  end

  def show
    @blog = Blog.find(params[:blog_id])
    @comments = Comment.all
    @comment = @blog.comments
  end

  def new
      @blog = Blog.find(params[:blog_id])
      @comment = @blog.comments.new
      if current_user === nil
      flash[:notice] = "you have to be signed in to comment."
      redirect_to blog_path(@blog)
      end
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to blogs_path }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to blogs_path
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/my_references_controller.rb
class MyReferencesController < ApplicationController
  def index
  @my_references = My_reference.all
  end

  def new
    @my_reference = My_reference.new()
  end

  def create
    @my_reference = My_reference.new(my_reference_params)
    @my_reference.save()
    respond_to do |format|
      format.html { redirect_to my_references_path }
      format.js
    end
  end

  private
    def my_reference_params
      params.require(:my_reference).permit(:name, :title, :phone, :address, :relationship)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
      @skill = Skill.find(params[:skill_id])
      @project = @skill.projects.new
    end

    def show
      @skill = Skill.find(params[:skill_id])
      @project = Project.find(params[:id])
    end


  def create
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new(project_params)
    if @project.save
      redirect_to skill_path(@project.skill)
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project successfully updated!"
      redirect_to skill_path(@project.skill)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project successfully deleted."
    redirect_to skill_path(@project.skill)
  end

  private
    def project_params
      params.require(:project).permit(:name, :link, :description)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new()
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save()
      redirect_to skills_path
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to skills_path
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to skills_path
  end

  private
    def skill_params
      params.require(:skill).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_blog.html.erb
<div id="blog_<%= blog.id %>">
  <h3><%= blog.title%></h3>
  <h6><%= blog.created_at %></h6>
  <p><%= blog.body%></p>
  <div class="comment-buttons">
    <span><%= button_to blog.comments.count.to_s + " Comments", blog_comment_path(blog, blog.comments), method: :get, id: "comments_link", remote: true %></span>
    <span><%= button_to "Add Comment", new_blog_comment_path(blog.id), method: :get, id: "add_comment_link", remote: true %></span>
  </div>

  <% if user_admin %>
    <span><%= link_to 'Edit', edit_blog_path(blog), remote: true %> |</span>
    <span><%= link_to "Delete", blog_path(blog), :method => "delete", remote: true %></span>
  <% end %>

    <div class="comments">
    </div>

</div>

app/views/blogs/_form.html.erb
<%= render "layouts/errors", :object => @blog %>

<%= form_for @blog, remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/blogs/create.js.erb
$('#new_blog').hide();
$('#blogs').append('<%= j render (@blog) %>');

app/views/blogs/destroy.js.erb
$('#blog_<%= @blog.id %>').remove();

app/views/blogs/edit.html.erb
<h1>Edit your project</h1>

<%= render 'form'%>

app/views/blogs/edit.js.erb
$('#blog_<%= @blog.id %>').before('<%= j render("form") %>');

app/views/blogs/index.html.erb
<% content_for(:navbar) do %>
<%= link_to "Add blog", new_blog_path, remote: true %>
<% end %>

<h1>Blog Page</h1>
<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h1>Add a blog post form</h1>

<%= render "form"%>

app/views/blogs/new.js.erb
$('#blogs').before('<%= j render("form") %>');

app/views/blogs/show.html.erb
<h1><%= @blog.title%></h1>
<h6><%= @blog.created_at%></h6>
<p><%= @blog.body%></p>

<%= link_to "Comment", new_blog_comment_path(@blog)%>

  <% @blog.comments.each do |comment| %>
    <li><%= comment.body %></li>
    <% user = User.find(comment.user_id) %>
      by <%= user.username %>
      <% if user_admin %>
        | <%= link_to 'Edit', edit_blog_comment_path(user, comment) %> |
      <% end %>
  <% end %>

app/views/blogs/update.js.erb
$('#blog_<%= @blog.id %>').html('<%= j render (@blog) %>');

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
<li><%= comment.body %></li>
<% user = User.find(comment.user_id) %>
  by <%= user.username %>
</div>

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@blog, @comment], remote: true do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/create.js.erb
$('#new_comment').hide();
$('#add_comment_link').show();
$('#comments_link').prepend('<%= j render (@comment) %>');

app/views/comments/edit.html.erb
<h1>Edit your comment</h1>

<%= render 'form'%>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>

<li><%= comment.body %></li>
<% user = User.find(comment.user_id) %>
  by <%= user.username %>
<% end %>

app/views/comments/new.html.erb
<h1>Add a comment</h1>

<%= render "form"%>

app/views/comments/new.js.erb
$('#blog_<%= @blog.id %> .comments').hide();
$('#add_comment_link').hide();
$('#comments_link').show();
$('#blog_<%= @blog.id %>').after('<%= j render("form") %>');

app/views/comments/show.js.erb
$('#comments_link').hide()
$('#blog_<%= @blog.id %> .comments').html('<%= j render(@comment) %>')

app/views/language/index.html.erb
<h1>Kick-ass Programming skills:</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops! Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="/skills">Chase Reckling</a>

      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Blog", blogs_path%></li>
          <li><%= link_to "References", my_references_path%></li>
          <% if user_admin %>
            <li><%= yield(:navbar) %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
                     <ul class="dropdown-menu">
                       <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                       <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                     </ul>
                   </li>
                   <% else %>
                   <li><%= link_to "Sign up", new_user_registration_path %></li>
                   <li><%= link_to "Login", new_user_session_path %></li>
                 <% end %>
        </ul>

      </div>
    </div>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/my_references/_form.html.erb
<%= render "layouts/errors", :object => @my_reference %>

<%= form_for @my_reference, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :title %>
  <%= f.text_area :title %>
  <%= f.label :phone %>
  <%= f.text_area :phone %>
  <%= f.label :address %>
  <%= f.text_area :address %>
  <%= f.label :relationship %>
  <%= f.text_area :relationship %>
  <%= f.submit %>
<% end %>

app/views/my_references/_my_reference.html.erb
<div id="my_reference_<%= my_reference.id %>">
  <h3><%= my_reference.name%></h3>
  <li><%= my_reference.title%></li>
  <li><%= my_reference.phone%></li>
  <li><%= my_reference.address%></li>
  <li><%= my_reference.relationship%></li>
</div>

app/views/my_references/create.js.erb
$('#new_my_reference').hide();
$('#my_references').append('<%= j render (@my_reference) %>');

app/views/my_references/index.html.erb
<% content_for(:navbar) do %>
<%= link_to "Add reference", new_my_reference_path, remote: true %>
<% end %>

<h1>References Page</h1>

<div id="my_references">
    <% @my_references.each do |my_reference| %>
      <%= render my_reference %>
    <% end %>
</div>

app/views/my_references/new.js.erb
$('#my_references').before('<%= j render("form") %>');

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @project) %>

<%= form_for [@skill, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/new.html.erb
<h1>Add a Project</h1>

<%= render 'form'%>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<% content_for(:navbar) do %>
<li><%= link_to "Edit", edit_skill_project_path(@skill, @project) %></li>
<li><%= link_to "Delete", skill_project_path(@skill, @project), :method => "delete" %></li>
<% end %>

<li> <%= link_to @project.link, @project.link %> </li>
<li> <%= @project.description %>

app/views/references/create.js.erb
$('#references').append('<%= j render (@reference) %>');

app/views/references/index.html.erb
<% content_for(:navbar) do %>
<%= link_to "Add reference", new_reference_path, remote: true %>
<% end %>

<h1>References Page</h1>

<div id="references">
</div>

app/views/references/new.html.erb
<h1>References Form</h1>

<%= render "form" %>

app/views/references/new.js.erb
$('#references').before('<%= j render("form") %>');

app/views/skills/_form.html.erb
<%= render "layouts/errors", :object => @skill %>

<%= form_for @skill do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%=  render "form" %>

app/views/skills/index.html.erb
<% content_for(:title) do %>
  Chase Reckling
<% end %>

<% content_for(:navbar) do %>
  <li><%= link_to "Add skill", new_skill_path(@skill) %></li>
<% end %>

<h1>About Me</h1>
<p>Rope's end hang the jib Nelsons folly Blimey loaded to the gunwalls me parley league topgallant lookout. Hang the jib wherry deadlights coffer furl piracy broadside scallywag yo-ho-ho loaded to the gunwalls. Scuppers parrel bilged on her anchor hardtack Chain Shot gally fathom cable bounty tack.
Lanyard poop deck Sea Legs bowsprit run a rig Spanish Main reef sails hornswaggle barkadeer Buccaneer. Cutlass driver scourge of the seven seas topgallant gibbet hardtack sloop handsomely Buccaneer Plate Fleet. Nelsons folly booty squiffy me lass six pounders black spot careen bucko square-rigged.
To go on account rutters gangway bilged on her anchor loaded to the gunwalls spanker sheet clipper gabion dead men tell no tales. Barque dance the hempen jig tackle lee wherry squiffy shrouds code of conduct mutiny yawl. Draft carouser barque measured fer yer chains long boat cog ho avast jib boatswain.</p>

<hr>

<h3>Programming Skills:</h3>

<ul>
  <% @skills.each do |skill| %>
    <h3><%= link_to skill.name, skill_path(skill) %></h3>
    <span><%= skill.description %></span>
  <% end %>
</ul>

app/views/skills/new.html.erb
<h3>Add a new skill</h3>



<%= render "form" %>

<hr>

<%= button_to "Back to homepage", skills_path, method: "get" %>

app/views/skills/show.html.erb
<% content_for(:title) do %>
  <%= @skill.name %> Projects
<% end %>

<% content_for(:navbar) do %>
  <li><%= link_to "Add project", new_skill_project_path(@skill) %></li>
  <li><%= link_to "Edit", edit_skill_path(@skill) %></li>
  <li><%= link_to "Delete", skill_path(@skill), :method => "delete" %></li>

<% end %>

<h1><%= @skill.name %></h1>

<% if @skill.projects.any? %>
  <h4>Here are the projects for this skill:</h4>

  <ul>
    <% @skill.projects.each do |project| %>
      <h4> <%= link_to  project.name, skill_project_path(@skill, project) %> </h4>
    <% end %>
  </ul>
<% else %>
  <p>There are no projects yet!</p>
<% end %>

<p><%= link_to "Return to homepage", skills_path %></p>